### ISSUE TITLE
.describe doesn't work if k8s template creates multiple resources

### ISSUE THREAD

**Issue by nictuku** [bazelbuild/rules_k8s#113]
I have k8s jsonnet templates that output two resources: a deployment and a service.

That works fine for `. apply` actions, but the `.describe` ones seem to get confused:

```
$ bazel run //examples/hellohttp/go/server:go-hellohttp_deploy.describe
INFO: Analysed target //examples/hellohttp/go/server:go-hellohttp_deploy.describe (157 packages loaded).
INFO: Found 1 target...
Target //examples/hellohttp/go/server:go-hellohttp_deploy.describe up-to-date:
  bazel-bin/examples/hellohttp/go/server/go-hellohttp_deploy.describe
INFO: Elapsed time: 13.445s, Critical Path: 0.53s
INFO: Build completed successfully, 1 total action

INFO: Running command line: bazel-bin/examples/hellohttp/go/server/go-hellohttp_deploy.describe
Error from server (NotFound): deployments.extensions "go-hellohttp-app-deployment\ngo-hellohttp-svc" not found
ERROR: Non-zero return code '1' from command: Process exited with status 1
```

The underlying reason is that the `kubectl create --dry-run` returns multiple resources but the describe script expects only one.

```
$ kubectl create --dry-run -f "${RUNFILES}/__main__/test_cd_deploy.yaml" | cut -d'"' -f 2
test-cd-app-deployment
test-cd-svc
```

Code that consumes this:

``` 
RESOURCE_NAME=$(kubectl create --dry-run -f "${RUNFILES}/__main__/test_cd_deploy.yaml" | cut -d'"' -f 2)

kubectl --cluster="fooo" --namespace="$(cat ${RUNFILES}/__main__/test_cd_deploy.describe.namespace-name)" \
    describe deployment "${RESOURCE_NAME}"
```

Should we just replace [this](https://github.com/bazelbuild/rules_k8s/blob/d6bca8104db9890d66e0b0aa1a3c558d985ed8d3/k8s/describe.sh.tpl#L26) with a for loop?

**Comment by nictuku** [comment]
Oh. At least in my case, a naive for loop wouldn't work because my yaml has different kinds of objects, so doing `describe deployment foo` and  `describe deployment bar` wouldn't work since each is of a different kind (deployment, service).

**Comment by fejta** [comment]
If you specify kind we will describe that kind. If you do not specify a kind I don't think it is worth trying to parse the files to figure out all the objects and describe them.

Feel free to reopen with a contribution to that effect if needed.
