### ISSUE TITLE
rules_nodejs can't be deployed using rules_k8s: wrong platform

### ISSUE THREAD

**Issue by nictuku** [bazelbuild/rules_k8s#115]
This is most likely a user problem, so apologies for opening an issue. I bet there's some piece of documentation I didn't read that explains this, but I can't find it.

I'm building a nodejs app from OSX and trying to deploy it to kubernetes using `rules_k8s`.

It almost works, except that the node doesn't start because of this error:

```
/app/examples/hellohttp/nodejs/nodejs-hellohttp_image.binary: line 147: /app/examples/hellohttp/nodejs/nodejs-hellohttp_image.binary.runfiles/com_github_yourbase_yourbase/external/nodejs/bin/node: cannot execute binary file: Exec format error
/app/examples/hellohttp/nodejs/nodejs-hellohttp_image.binary: line 147: /app/examples/hellohttp/nodejs/nodejs-hellohttp_image.binary.runfiles/com_github_yourbase_yourbase/external/nodejs/bin/node: Success
```

It looks like the `node` binary being deployed wasn't built for the right platform where k8s is running (linux with amd64, normal Google GKE nodes).

The command I'm using to make the deployment:

```
bazel run --cpu=k8 //examples/hellohttp/nodejs:nodejs-hellohttp_deploy.apply
```

I tried with other combinations of `--platforms` or `--cpu` but I couldn't get it to work.

The argument that felt like the closest was this:

```
$ bazel run --platforms=@bazel_tools//platforms:linux //examples/hellohttp/nodejs:nodejs-hellohttp_deploy.apply
ERROR: While resolving toolchains for target //examples/hellohttp/nodejs:nodejs-hellohttp_deploy.apply: Target constraint_value rule @bazel_tools//platforms:linux was found as the target platform, but does not provide PlatformInfo
ERROR: Analysis of target '//examples/hellohttp/nodejs:nodejs-hellohttp_deploy.apply' failed; build aborted: Target constraint_value rule @bazel_tools//platforms:linux was found as the target platform, but does not provide PlatformInfo
INFO: Elapsed time: 0.255s
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
```

This says there was a toolchain problem, and says something about missing PlatformInfo, but it doesn't say anything about how do I fix it. :-(

For what is worth, with Go I had similar problems, and they were solved by passing `--experimental_platforms=@io_bazel_rules_go//go/toolchain:linux_amd64` to the bazel run command.

How do I make something similar work for nodejs? I'm happy to dig further and fix problems, but what command was at least supposed to work for this?

Any pointers would be much appreciated!

For reference, I also asked this question in SO and I'll update [that](https://stackoverflow.com/questions/48880625/bazel-rules-nodejs-cant-be-deployed-using-rules-k8s-wrong-platform) if/when there's an answer here.

**Comment by mattmoor** [comment]
Can you open this issue on `rules_nodejs`, as `nodejs_image` is really just pass-thru to that repository (as with `rules_go`)?
