### ISSUE TITLE
An :object.reload target

### ISSUE THREAD

**Issue by xoebus** [bazelbuild/rules_k8s#119]
We chatted about this really briefly in Slack but I'm filing this here so there's something to track.

During development it's sometimes nice to get a fresh start in whatever system you've deployed. This can be accomplished today relatively easily with an `:object.delete` followed by an `:object.create`. Would it be valuable to have this as its own target?

```
$ bazel run //:everything.reload
```

If this sounds valuable then I'm happy to work on a PR for this.

**Comment by mattmoor** [comment]
I think having this on `k8s_objects` and `k8s_object` would be useful :)

**Comment by fejta** [comment]
This is what `.replace` does -- delete followed by create.

https://github.com/bazelbuild/rules_k8s/blob/0a04716c226d0173bf7035965d9010871d39142b/k8s/object.bzl#L551

https://github.com/bazelbuild/rules_k8s/blob/0a04716c226d0173bf7035965d9010871d39142b/k8s/objects.bzl#L100
