### ISSUE TITLE
build_tag_filters not working as expected

### ISSUE THREAD

**Issue by ychen-atlassian** [bazelbuild/rules_k8s#123]
Similar to https://github.com/bazelbuild/rules_docker/issues/269, it seems like tags aren't being propogated the rules generated by k8s_object:

```
//blah.replace
//blah.describe
//blah.delete
//blah.reversed
//blah.create
//blah.apply
//blah
```

E.g. given this:

```
my_custom_rule(
    name = "some_template",
    tags = ["exclude_from_tests"],
)

k8s_object(
    name = "blah",
    cluster = "my-cluster",
    kind = "deployment",
    namespace = "blahns",
    template = ":some_template",
    tags = ["exclude_from_tests"],
)
```

There is still a dependency on "my_custom_rule" even though all rules are marked as "exclude_from_tests", as the additional rules do not have the tag applied.

**Comment by ash2k** [comment]
@ychen-atlassian this can be closed now, I think.
