### ISSUE TITLE
using the sha256 digest of an image in a Deployment object

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_k8s#124]
I didn't see this documented, but, in the templating stuff, is there a variable for the sha256 of the an container_image (etc.) object? I'd like to use it now that k8s supports using those in their Deployment objects.

**Comment by mattmoor** [comment]
I'm not entirely sure what you mean?

When you write:
```
k8s_object(
    name = "foo",
    template = "bar.yaml",
    images = {
        "foo:latest": "//cmd/blah:image",
    },
)
```

... the image `//cmd/blah:image` is published to `{image_chroot}/foo:latest` and its **digest** is substituted for `foo:latest` in `bar.yaml`.

The same resolver will also attempt to resolve image tags to digests even when we aren't publishing them.

Here you'd see that if you `bazel run :foo` (without any trailing `.action`).


If you are looking for something else, I could use some more help understanding what that is?

**Comment by jmhodges** [comment]
Duh, duh, I knew that. Sorry, bad bug that I meant to confirm before closing. Just been a while since I had played with this.
