### ISSUE TITLE
Support `--token` argument to kubectl

### ISSUE THREAD

**Issue by greggdonovan** [bazelbuild/rules_k8s#126]
Normally we run `kubectl` via `kubectl --token $K8S_TOKEN apply ...` where `K8S_TOKEN` is a value pulled pulled from a Jenkins credentials store.

[`apply.sh.tpl`](https://github.com/bazelbuild/rules_k8s/blob/master/k8s/apply.sh.tpl#L27) doesn't seem to have a hook to pass it in. 

I'm happy to make a PR if you can suggest an approach. I've got `--token` hacked in to a fork at the moment.

**Comment by chrislovecnm** [comment]
https://github.com/bazelbuild/rules_k8s/pull/224

Is merged. Closing

Let us know how it works out!
