### ISSUE TITLE
Pushing images to *.azurecr.io

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_k8s#128]
I'm having trouble pushing images to an azure container registry.  Any recommended way to debug this?

```
CRITICAL:root:Error publishing provided image: Bad status during token exchange: 400
```

This works, but does not seem to help:

```
$ az acr login my-cr
Login Succeeded
```

**Comment by pcj** [comment]
Looks like I need to use the service principal creds:

```
$ docker login myacr.azurecr.io -u $SERVICE_PRINCIPAL_APP_ID -p $CLIENT_SECRET
```

But then when I try and `bazel run //my-app/k8s:pod.apply`, I get the following:

```
Malformed JSON response: {"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNSV0c6N...nPl4tOQPmqfzhzzkFLKAsSjg9GLn72bo4iXov843SJhGU78pqiyCsRBUxdBZcRu9DLclfHp4w-cat-VgnRF3Xcxf9M2oyJmS4zylK60d8MzBwUycbe6K3fiCH9sNdRKzb4FwFKvE5g"}
```

**Comment by pcj** [comment]
Oh.  That looks like an easy fix.  I'm happy to submit a PR, but might be faster if this is something a gcr or googler wants to take care of.  I'd just do something like:

```python
token = wrapper_object['token'] or wrapper_object['access_token']
_CheckState(token is not None, "...")

with self._lock:
      # We have successfully reauthenticated.
      self._creds = v2_2_creds.Bearer(token)

```

**Comment by jonjohnsonjr** [comment]
Yep, should be pretty simple. I'll pick this up internally -- thanks!

**Comment by pcj** [comment]
FWIW, I can confirm this fixes the issue (not extensively tested, but it seems to work)

```python
    wrapper_object = json.loads(content)
    token = wrapper_object.get("token")
    if not token:
      token = wrapper_object.get("access_token")
    
    _CheckState(len(token) > 0,
                'Malformed JSON response (expected response to include token or access_token): %s' % content)

    with self._lock:
      # We have successfully reauthenticated.
      self._creds = v2_2_creds.Bearer(token)
```

**Comment by pcj** [comment]
Holy crap I didn't know there was a go implementation.  Sweet.

**Comment by fejta** [comment]
/assign @mattmoor 
Matt why was this closed and then reopened? Is this fixed perhaps?

**Comment by schoren** [comment]
Is this issue fixed? I'm currently getting this error:

`CRITICAL:root:Error publishing provided image: Bad status during token exchange: 401`

Is it possible to use my AAD user to login to docker? or is it necessary to use an SP?

Thanks

**Comment by schoren** [comment]
Ok, so I see that if I log in as a service principal, everything works fine. If using the credentials set by `az acr login` it returns this error:

`CRITICAL:root:Error publishing provided image: Bad status during token exchange: 401`

So i guess this is still not working. Is there any way to contribute to fix this issue?

**Comment by chrislovecnm** [comment]
Can someone confirm if this is resolved?

**Comment by schoren** [comment]
Still happening to me. Have to use a Service Principal and `docker login`

**Comment by jullianoacqio** [comment]
I have the same problem. 
Log in to the registry from ```az acr login``` does not work docker pull from bazel.
Docker login from the service principal works

**Comment by fejta** [comment]
rules_k8s does not push images. This is done by rules_docker (and its dependencies). Please work through that repo.

This looks vaguely relevant: https://github.com/bazelbuild/rules_docker#authentication

**Comment by jonjohnsonjr** [comment]
FWIW, this was probably fixed on the rules_docker side in https://github.com/bazelbuild/rules_docker/issues/1193
