### ISSUE TITLE
Fails to publish images to registries when registry port is specified

### ISSUE THREAD

**Issue by jszroberto** [bazelbuild/rules_k8s#131]
I was trying to use a local docker registry listening on `localhost:5000` and I discovered that these rules do not work if you specify a port

The reason is that the code identifies everything after the colon as the image tag. 

Config: 
```
image_chroot: localhost:5000/jszroberto
```
Error: 
```
CRITICAL:root:Error publishing provided image: Invalid tag: 5000/jszroberto/bazel-test, acceptable characters include:
```

**Comment by mattmoor** [comment]
This is actually a bug in the parsing logic of google/containerregistry when we're not being strict.

@dekkagaijin wanna TAL?

**Comment by mattmoor** [comment]
You should be able to work around this by suffixing `:latest`

**Comment by jszroberto** [comment]
@mattmoor right, it's in the registry client itself: https://github.com/google/containerregistry/blob/master/client/docker_name_.py#L197. Let me try it out and then close this issue here. Let me close this an track it in https://github.com/google/containerregistry/issues/83

**Comment by xuehuichao** [comment]
+1 on this. Also it'd be nice to include instructions/examples to work with minikube.

**Comment by chrislovecnm** [comment]
Is this a docker_rules issue?

**Comment by fejta** [comment]
Yes, pushing happens via rules_docker, please work through that repo: https://github.com/bazelbuild/rules_docker/issues
