### ISSUE TITLE
Proposal: Allow to specify kubectl context instead of cluster

### ISSUE THREAD

**Issue by burdiyan** [bazelbuild/rules_k8s#135]
It may be useful to allow to specify context for kubectl instead of cluster. And actually current docs are a little bit misleading, because it says "This should match the cluster name as it would appear in `kubectl config current-context`" but this command doesn't output anything related to cluster, only name of the context.

In our use case of GKE, we use `get-credentials` from `gcloud` to authenticate in the cluster, and then we use `kubectl config rename-context` to rename the complicated name to our standards. But we don't touch cluster names. So that's making things a little bit more complicated.

**Comment by jasongwartz** [comment]
FYI, I'm going to work on a PR to add the context parameter, so it would be possible to use either context or cluster or both.
