### ISSUE TITLE
k8s deployment clarification

### ISSUE THREAD

**Issue by clanstyles** [bazelbuild/rules_k8s#139]
```
load("@io_bazel_rules_k8s//k8s:object.bzl", "k8s_object")

k8s_object(
  name = "dev",
  kind = "deployment",

  # A template of a Kubernetes Deployment object yaml.
  template = ":deployment.yaml",

  # An optional collection of docker_build images to publish
  # when this target is bazel run.  The digest of the published
  # image is substituted as a part of the resolution process.
  images = {
    "gcr.io/rules_k8s/server:dev": "//server:image"
  },
)
```

I have a bunch of questions about the above example. We have a development and a production cluster. 

1. How can I specify what cluster to deploy to? Are the k8s_defaults in the ```WORKSPACE``` determining the cluster? 
2. How can I switch the cluster for development & production? 
3. I noticed that the object name "dev" is what you use to trigger the deployment ```bazel build :dev```, Do I need to add a type of prod if I want to assign it to another cluster?

**Comment by Globegitter** [comment]
1. There are different ways how to do it but it is all decided by the `cluster`/`context` attributes available on `k8s_object/k8s_defaults`. One can use `k8s_defaults` but does not have to, it probably makes sense to set it if there is only one cluster, or the cluster is somehow being set dynamically via make variables or stamping. We just wrapped the k8s_object in a macro to decide to which of our clusters to deploy.

2. By making use of make variables or stamping, or simply creating multiple k8s_object rules (or writing a macro that does that for you)

3. I think the names where chosen somewhat arbitrarily 

Hope that helps.

**Comment by clanstyles** [comment]
I was able to use stamping to solve my problem.
