### ISSUE TITLE
Dry run option

### ISSUE THREAD

**Issue by mariusgrigoriu** [bazelbuild/rules_k8s#145]
I'm wondering if there's interest (or opposition) to an optional parameter to k8s_object that would set the `--dry-run` flag to kubectl. This flag would be useful to validate your objects early in a long-running pipeline, so you don't have to wait until all your infrastructure is up only to find out you have malformed YAML or JSON.

**Comment by Globegitter** [comment]
Yeah it would be nice to have the option for a dry-run, but I wonder if that would be nicer to just be able to pass on at the end of `bazel run`. So `bazel run :target.apply -- --dry-run`, otherwise one would have to modify the `BUILD` file all the time, or have one target for a dry-run and another one for the real apply.

**Comment by chrislovecnm** [comment]
I would rather not modify a BUILD file to get this to run ...

**Comment by mariusgrigoriu** [comment]
Definitely not expecting to modify BUILD file every time you want to turn dry runs on/off. The original idea was to connect the arg to a make variable, but I do like @Globegitter's idea.

**Comment by mariusgrigoriu** [comment]
Oh and there's a new dry-run feature coming in kubectl

**Comment by chrislovecnm** [comment]
This PR will allow us to pass in arbitrary commands https://github.com/bazelbuild/rules_k8s/pull/174

Would that help us out??

**Comment by Globegitter** [comment]
Yep #174 could indeed fix the issue - I left a comment: https://github.com/bazelbuild/rules_k8s/pull/174#discussion_r228050717 as the `$@` in the `apply.sh.tpl ` would have to be moved after the `apply` keyword. But then it does indeed work very nicely.

**Comment by chrislovecnm** [comment]
Can we override arg in a build file rather than a $@?

**Comment by Globegitter** [comment]
@chrislovecnm I just mentioned it in #209 if we name the attribute `arg` then we can set it both in the build file (and bazel will apply the flags at runtime) and via the cli at the end as I showed above.

**Comment by chrislovecnm** [comment]
Closing, as we have this in master now
