### ISSUE TITLE
Pass arbitrary arguments to kubectl

### ISSUE THREAD

**Issue by mariusgrigoriu** [bazelbuild/rules_k8s#146]
#126 and #145 are requesting additional arguments to kubectl, and I suspect there will be more such issues in the future as the user base and the variety of scenarios grow. kubectl has many flags and it seems that we will be perpetually behind. Should we have a way to pass arbitrary arguments to kubectl?

**Comment by chrislovecnm** [comment]
https://github.com/bazelbuild/rules_k8s/pull/224

Is merged. Closing
