### ISSUE TITLE
Add --allow_unused_images resolver flag

### ISSUE THREAD

**Issue by calder** [bazelbuild/rules_k8s#161]
# Background

Some macros will instantiate `k8s_object(...)` multiple times with different SKUs. When an image is only used by some SKUs and not others, the default resolver dies when it doesn't find the image in a particular SKU's template:

https://github.com/bazelbuild/rules_k8s/blob/4348f8e28b70cf3aff7ca8e008e8dc7ac49bad92/k8s/resolver.py#L190-L195

For cases like this, it would be nice to be able to relax the unused image error.

# Proposal

Add an `--allow_unused_images` flag to `resolver.py`. Add a `resolver_args` parameter to `k8s_object` that allows arguments to be passed directly to the resolver. This would be useful for custom resolvers as well.

**Comment by fejta** [comment]
Can you give a concrete example of what you mean by multiple SKUs?

The image reference not found is usually an important safeguard against launching the wrong image and image typos.

**Comment by calder** [comment]
As a safeguard, it's a bit like a very sturdy guard rail on only one side of a road with cliffs on both sides. :-) (See #147) However, this change still leaves the guard rail on by default and just allows it to be disabled when it's more trouble than its worth.

Example: Let's say you want to generate deployment targets for the same service across multiple environments. To do this:
1. You describe environments in Jsonnet files that are compiled to JSON files by jsonnet_to_json targets.
2. You describe services in Jsonnet files that can consume configuration from the current environment.
3. To generate all deployment targets, you invoke a single macro with your service's Jsonnet file, a list of environments, and a list of image dependencies. The macro generates a jsonnet_to_json and k8s_object rule for each environment.

The problem arises when a service uses an image in only some environments. This is pretty common in test vs. production environments. In this case the k8s_object targets will fail in environments that don't use a listed image.

**Comment by calder** [comment]
@fejta: Friendly ping!
