### ISSUE TITLE
Do we need to specify cluster if context is being provided to unlock apply rule?

### ISSUE THREAD

**Issue by mariusgrigoriu** [bazelbuild/rules_k8s#167]
Today a user need to provide the cluster name to unlock apply and delete actions. Users can now pass in a context, which also provides a cluster name, but the user must still define a cluster attribute to get access to the extra actions. 

Should the additional actions be gated on context or cluster name attributes rather than just the cluster attribute?

**Comment by fejta** [comment]
Sounds reasonable to not require cluster if context is defined. Any chance you want to offer up a PR?

**Comment by benley** [comment]
I ran into this too, so here's a PR: https://github.com/bazelbuild/rules_k8s/pull/170
