### ISSUE TITLE
Run E2E tests from different PRs in different namespaces

### ISSUE THREAD

**Issue by erain** [bazelbuild/rules_k8s#173]
### The problem

Currently all e2e tests are running under the same namespace, which make them un-parallelizable. We want to have e2e tests from different PRs to be ran under different namespaces so that we can parallelize them. 

### Potential solution

To differentiate different PRs we have, we can use Make Variables. When the job runs in prow, the PR number is available as an environment variable PULL_NUMBER: https://github.com/kubernetes/test-infra/tree/master/prow#job-environment-variables. Or we could also use BUILD_NUMBER

In [test-infra](https://github.com/kubernetes/test-infra/tree/master/prow) we have:
- https://github.com/kubernetes/test-infra/blob/master/hack/print-workspace-status.sh
- and have https://github.com/kubernetes/test-infra/blob/4e1ff506ac969d6c609b86899a943ba4fb7d1b1f/.bazelrc#L1

Also https://github.com/bazelbuild/rules_k8s#developer-environments talks about the print-workspace-status.sh trick. 
So We'd do something like:
```
cat <<EOF
E2E_NAMESPACE=$USER-${BUILD_NUMBER:-0}
EOF
```

then switch `_NAMESPACE="{E2E_NAMESPACE}"`

**Comment by chrislovecnm** [comment]
Closing - fixed
