### ISSUE TITLE
Build is failing on master

### ISSUE THREAD

**Issue by systemlogic** [bazelbuild/rules_k8s#183]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/bazelbuild_rules_k8s/174/pull-rules-k8s-e2e/260/

ERROR: The following image references were not found in '/root/.cache/bazel/_bazel_prow/0996f4cdf646bf91686374917a22c2ea/execroot/io_bazel_rules_k8s/bazel-out/k8-fastbuild/bin/examples/hellohttp/error-on-run.runfiles/io_bazel_rules_k8s/examples/hellohttp/deployment.yaml'

**Comment by systemlogic** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/bazelbuild_rules_k8s/174/pull-rules-k8s-e2e/260/

**Comment by chrislovecnm** [comment]
I am able to build master on OSX.  It is just during e2e that we are having issues?

**Comment by fejta** [comment]
Error is:
```console
Checking response from service: DEMO  matches: DEMO28977<space>
```

**Comment by fejta** [comment]
@systemlogic  https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-rules-k8s-e2e

suggests it is most likely your PR that is the problem

**Comment by fejta** [comment]
Which is exactly what I said a month ago: https://github.com/bazelbuild/rules_k8s/pull/174#issuecomment-420979701

**Comment by chrislovecnm** [comment]
Thanks @fejta
