### ISSUE TITLE
Set kubeconfig location

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_k8s#190]
Add to `k8s_object` a field allows the user to specify which kubeconfig file kubectl accesses.  We could simply set the command line flag `kubectl --kubeconfig my-file`.

/cc @pcj

**Comment by chrislovecnm** [comment]
https://github.com/bazelbuild/rules_k8s/pull/174 will address this

**Comment by chrislovecnm** [comment]
https://github.com/bazelbuild/rules_k8s/pull/224 Is merged. Now we can set this

**Comment by rohansingh** [comment]
One remaining issue is that it's not possible to use a generated kubeconfig, at least from what I can see.

For example, I have a target elsewhere that outputs a config file, and I want to pass this as `--kubeconfig`. But there's no way to specify that my `k8s_object` should depend on that target.
