### ISSUE TITLE
Multiple branches in GitHub

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_k8s#197]
Any reason that we have a ton of branches on this repo?

**Comment by chrislovecnm** [comment]
https://github.com/bazelbuild/rules_k8s/branches/all

These are old branches, like really old.  Anyone mind me cleaning house or do we need to ensure that we do not loose any code.

**Comment by erain** [comment]
I think all the branches are because of historical reasons. On one hand I think they are worth cleanup, on the other hand we need to audit each one of them before deleting it. 

Could you help with this? Maybe starting with make sure they are not used in the current issues.

**Comment by erain** [comment]
I could review these branches as well. My plan is to go through them, make a list of obvious not useful one, and another list maybe contains useful code and double check with @mattmoor .

**Comment by fejta** [comment]
Just one branch
