### ISSUE TITLE
Errors in e2e are a tad confusing

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_k8s#201]
I do not think this is an error, but it is confusing.

```
Error from server (NotFound): deployments.apps "hello-grpc-staging" not found
```

See https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/bazelbuild_rules_k8s/200/pull-rules-k8s-e2e/300

**Comment by fejta** [comment]
Fixed by https://github.com/bazelbuild/rules_k8s/pull/570
