### ISSUE TITLE
Toolchain resolution fails with cross-compilation

### ISSUE THREAD

**Issue by pierreis** [bazelbuild/rules_k8s#215]
I'm trying to set cross-compilation, so that I can build locally on a Mac the Go sources to be ran on a local Kubernetes cluster. The kubectl client is running on the Mac.

Running Go compilation as well as creating the Docker image work:

```
$ bazel build --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //deploy/docker/user_data:image
INFO: Analysed target //deploy/docker/user_data:image (0 packages loaded).
INFO: Found 1 target...
Target //deploy/docker/user_data:image up-to-date:
  bazel-bin/deploy/docker/user_data/image-layer.tar
INFO: Elapsed time: 0.375s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

However, a wildcard build fails:

```
$ bazel build --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //...
ERROR: While resolving toolchains for target //deploy/k8s:user_data_deployment.create: no matching toolchains found for types @io_bazel_rules_k8s//toolchains/kubectl:toolchain_type
ERROR: Analysis of target '//deploy/k8s:user_data_deployment.create' failed; build aborted: no matching toolchains found for types @io_bazel_rules_k8s//toolchains/kubectl:toolchain_type
INFO: Elapsed time: 0.126s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Any hint on how to make k8s work with Go cross-compilation?

Thanks.

**Comment by smukherj1** [comment]
@alex1545 Likely related to #210 

Think the issue is related to the kubernetes toolchain rule not supporting the linux_amd64 platform. I'm guessing the following will probably work
`
bazel build --platforms="@bazel_tools//platforms:linux,@bazel_tools//platforms:x86_64" //...
`
not 100% sure if the above is the right way to specify multiple platform targets

**Comment by smukherj1** [comment]
Actually never mind my previous comment, from https://github.com/bazelbuild/rules_go/blob/master/go/platform/list.bzl I see linux_amd64 I see @io_bazel_rules_go//go/toolchain:linux_amd64 has the constraints "linux" and "x86_64" which is what the kubectl toolchain requires (see here https://github.com/bazelbuild/rules_k8s/blob/master/toolchains/kubectl/BUILD#L32)

Do you have the following in your WORKSPACE files?
`load("@io_bazel_rules_k8s//k8s:k8s.bzl", "k8s_repositories")

k8s_repositories()
`
This code ensures the kubectl toolchain is registered in your bazel project

**Comment by pierreis** [comment]
Yes.

Workspace is set as follows (for the Docker / K8S part):

```
# ================================================================
# Docker
# ================================================================

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "29d109605e0d6f9c892584f07275b8c9260803bf0c6fcb7de2623b2bedc910bd",
    strip_prefix = "rules_docker-0.5.1",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.5.1.tar.gz"],
)

load("@io_bazel_rules_docker//container:container.bzl", "container_pull", container_repositories = "repositories")

container_repositories()

# ================================================================
# K8s
# ================================================================

git_repository(
    name = "io_bazel_rules_k8s",
    commit = "489310b9bc69a8a79ec4768be84a65037fe5ce9b",
    remote = "https://github.com/bazelbuild/rules_k8s.git",
)

load("@io_bazel_rules_k8s//k8s:k8s.bzl", "k8s_repositories")

k8s_repositories()

load("@io_bazel_rules_k8s//k8s:k8s.bzl", "k8s_defaults")

k8s_defaults(
  name = "k8s_deploy",
  kind = "deployment",
  cluster = "docker-for-desktop-cluster",
  namespace = "default",
)
```

**Comment by smukherj1** [comment]
I think it will help if we could get a test project that reproduces this

**Comment by pierreis** [comment]
Sure. Here is a minimal example of the issue: https://github.com/pierreis/k8s-cross-compile-demo

```
$ bazel run --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //deploy:deployment.create
ERROR: While resolving toolchains for target //deploy:deployment.create: no matching toolchains found for types @io_bazel_rules_k8s//toolchains/kubectl:toolchain_type
ERROR: Analysis of target '//deploy:deployment.create' failed; build aborted: no matching toolchains found for types @io_bazel_rules_k8s//toolchains/kubectl:toolchain_type
INFO: Elapsed time: 0.082s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by smukherj1** [comment]
Interesting, does not reproduce when I run it on linux. I would have thought the host platform would be irrelevant because I was assuming the toolchain resolution would use the target platform. I tried it from a mac and I did reproduce the error.

However, when I removed the platform requirement, the toolchain resolution succeeded. This is because in rules_k8s we do register a k8s toolchain that's compatible with osx. So it's unclear why toolchain resolution fails when the target platform is explicitly specified to be linux/x86_64 and the host platform is osx but succeeds when target platform is explicitly specified to be linux/x86_64 and the host platform is linux/x86_64. @katre any ideas?

**Comment by smukherj1** [comment]
Thanks a lot for explaining the issue @katre 

@nlopezgi @alex1545 I think the kubectl toolchain actually doesn't care about the host platform and does care about the target platform. This is because the build in rules_k8s is only being used to generate binaries which have invocations of the k8s toolchain. The invocations are only expected to run in the target platform. So I think the right thing to do here would be to remove the exec_compatible_with constraints for the kubectl toolchain. I'll create a PR for this

**Comment by nlopezgi** [comment]
I agree the constraint should not be necessary.

**Comment by pierreis** [comment]
Awesome, thanks all.
@smukherj1, I can submit the pull request, removing the constraint.

**Comment by pierreis** [comment]
> Thanks a lot for explaining the issue @katre
> 
> @nlopezgi @alex1545 I think the kubectl toolchain actually doesn't care about the host platform and does care about the target platform. This is because the build in rules_k8s is only being used to generate binaries which have invocations of the k8s toolchain. The invocations are only expected to run in the target platform. So I think the right thing to do here would be to remove the exec_compatible_with constraints for the kubectl toolchain. I'll create a PR for this



> Thanks a lot for explaining the issue @katre
> 
> @nlopezgi @alex1545 I think the kubectl toolchain actually doesn't care about the host platform and does care about the target platform. This is because the build in rules_k8s is only being used to generate binaries which have invocations of the k8s toolchain. The invocations are only expected to run in the target platform. So I think the right thing to do here would be to remove the exec_compatible_with constraints for the kubectl toolchain. I'll create a PR for this

Actually, giving a thought about this, I'm not sure I do agree with that. Why would the scripts be expected to be executed on the target platform?
I would intuitively have said that you will typically `bazel build` and `bazel run` on the same platform ; that is, we only care about the exec platform, and should be removing the `target_compatible_with` attributes as @katre suggested.

In the case of #218, the change fixed the issue mostly because it fixed the toolchain resolution. Does not mean that the chosen toolchain is the correct one (doesn't matter much for bash).

**Comment by pierreis** [comment]
That would also align with the comments made in #235

**Comment by smukherj1** [comment]
According to my understanding, the host platform refers to the platform the build is being issued from (osx in your case), the execution platform refers to the platform the build actions are running on (osx in your case but might be different from host in other scenarios) and the target platform is the platform the binary produced in the build are expected to run on (linux in your case).

In our case, the kubectl command is never executed during bazel build and thus the execution platform isn't relevant. The bazel build however produces scripts that have invoke kubectl. These invocations are run with "bazel run" which run on the target platform. Thus, the kubectl toolchain resolution needs to be done according to the specified target platform.

**Comment by pierreis** [comment]
Actually, I think we do agree here, the problem seems to be that we might have three execution platforms here:

– The platform on which `bazel build` runs
– The platform on which `bazel run` runs
– And the platform on which the generated binaries from other tasks run

The major issue I see here is that building the k8s scripts will also typically trigger the build of the image ; both potentially being different, I'm not sure how to fix this issue.

I would only assume that in most of the cases, you would run both `build` and `run` on the same platform. Either because you are on a CI system or a local dev machine (my case). There might indeed be some edge cases here, but I'm not sure to see these.
