### ISSUE TITLE
kubectl tool chain building kubectl from source

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_k8s#227]
Hi all

I know that some of us would like the capability for a specific deployment to use a specific version of kubectl.  

1. download https://github.com/kubernetes/kubernetes
1. checkout correct version of kubernetes
1. bazel build //cmd/kubectl/...
1. rejoice

### Requirements

1. set flag to build kubectl.
1. set flag with which version of k8s to use.  SHA?
1. we need to probably have the capability to use multiple different version of kubectl within the same build.  Not sure if we can, but it is an idea. 

### Pre work

I have built and run kubectl on osx and linux (linux container on osx).  Zero problems.  I have not tested windows.

**Comment by nlopezgi** [comment]
All of the above should now be possible with the toolchain rules we recently added (including doing multiple versions of kubectl as part of the same build; this will be done via platforms and exec_compatible_with statements, though doing that properly will require some interesting tinkering). We will start working on this soon. First thing will be to provide attrs to download and build from sources an provide version details. If anyone has feelings as to how the kubernetes version should be specified (commit/release + sha sounds like a good starting point | use latest release). The first approach will be for this to be opt-in (default will remain to look for kubectl on path), until we have confirmation this will work for all users.

**Comment by nlopezgi** [comment]
fyi @alex1545

**Comment by chrislovecnm** [comment]
I think we need to use sha for a specific commit

**Comment by nlopezgi** [comment]
I explored today if building a kubectl binary via the toolchain rule could work.
I was able to get my rule to pull the kubernetes repo as part of the toolchain config rule. However, building kubectl as an external repo is not possible. I found the following issues:
- the build depends on an @org_golang_x_tools repo. I could not find out where this is being pulled (perhaps in a repository_rule?), however, I could hack around this by copying it from the kubernetes project directly
- the repo is using genrules (e.g. vendor/k8s.io/apimachinery/pkg/util/sets/BUILD:23) which are running go binaries produced by other build steps, but are not referencing these properly when used in an external repo. I got this error message: 

import "./vendor/k8s.io/apimachinery/pkg/util/sets/types": cannot find package "./vendor/k8s.io/apimachinery/pkg/util/sets/types" in:
        /usr/local/google/home/<...>/ffcac8bde6710ff680ff645bb4ae7c92/sandbox/linux-sandbox/30/execroot/io_bazel_rules_k8s/vendor/k8s.io/apimachinery/pkg/util/sets/types

I'll open up an issue in the kubernetes repo.

**Comment by chrislovecnm** [comment]
What the build command you executed @nlopezgi?

**Comment by nlopezgi** [comment]
created https://github.com/kubernetes/kubernetes/issues/71290

**Comment by nlopezgi** [comment]
to repro some of the issues I saw, you just need to create a new Bazel project, and add to the workspace:

```
http_archive(
     name = "io_kubernetes",
     sha256 = "4737d3b10b27e391924f89b5ac3aaa5470619b92b75fe1ff5210cc30c56e2e53",
     strip_prefix = "kubernetes-1.10.10",
     urls = ["https://github.com/kubernetes/kubernetes/archive/v1.10.10.tar.gz"]
 )
```

and then try to run 
`bazel build @io_kubernetes//cmd/kubectl:kubectl`

**Comment by nlopezgi** [comment]
(note I was able to successfully compile the kubernetes project if I just pulled that from github and built it with  `bazel build cmd/kubectl:kubectl`)

**Comment by chrislovecnm** [comment]
For d/l latest stable release 

curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl

The words linux and and64 can be replaced with the correct platforms

To download a specific version simply replace the version number like

curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kubectl

From

https://kubernetes.io/docs/tasks/tools/install-kubectl/

**Comment by ixdy** [comment]
you can use `https://dl.k8s.io` in place of `https://storage.googleapis.com/kubernetes-release`, too.
