### ISSUE TITLE
kubectl tool chain pulling pre-built kubectl

### ISSUE THREAD

**Issue by nlopezgi** [bazelbuild/rules_k8s#231]
related to https://github.com/bazelbuild/rules_k8s/issues/227
Spinning up this issue just to focus on adding feature to pull pre-built kubectl (related issues it to build from srcs).
Copy of relevant info from related issues:

@chrislovecnm commented:
For d/l latest stable release

curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl

The words linux and and64 can be replaced with the correct platforms

To download a specific version simply replace the version number like

curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kubectl

From

https://kubernetes.io/docs/tasks/tools/install-kubectl/
@ixdy commented: 
you can use `https://dl.k8s.io` in place of `https://storage.googleapis.com/kubernetes-release`, too.
for example you can use something like https://dl.k8s.io/release/v1.12.2/bin/linux/amd64/kubectl for the v1.12.2 kubectl for linux/amd64.

Note that the official macOS kubectl binaries (as well as the ones built via bazel) are still affected by https://github.com/kubernetes/kubernetes/issues/71290

see also: https://github.com/bazelbuild/rules_k8s/pull/229

**Comment by Toxicable** [comment]
Would be awesome to see some movement here.
If we could get Bazel to manage the version of `kubectl` being used similar to how we do in `rules_nodejs` for the `nodejs` binary, that would be awesome for keeping our builds hermetic, also making our workspace setting that little bit easier

**Comment by nlopezgi** [comment]
Hi @Toxicable 
We now support several ways of obtaining the kubectl tool. Please see here for details:
https://github.com/bazelbuild/rules_k8s/tree/master/toolchains/kubectl
and let us know if the alternatives there (detect from path, build from source, download prebuilt) do not satisfy your use case. I'd forgotten to close this issue, but closing now. Let me know to reopen if any use cases are not covered.

**Comment by Toxicable** [comment]
Ah yes, awesome, looks like the download prebuilt will work for us pretty well.
Only downside I see here is that I don't see a way to handle more than one platform, for example macos and linuxsince you can only specify the one binary

**Comment by nlopezgi** [comment]
hmm, you're right. We had not thought about that use case. We currently dont have plans to build more toolchain related features. But I'd be happy to work with you to design and implement a better way to do the toolchains to support your use case. For now, I think we can open up a new issue specifically asking for support for this new use case and move the conversation there. Thanks for noting this!
