### ISSUE TITLE
Add documentation for kubectl toolchain changes

### ISSUE THREAD

**Issue by samschlegel** [bazelbuild/rules_k8s#234]
The changes in #229 cause a breakage if `rules_go` has not been pulled in, and this is not currently mentioned in the Getting Started. It is also non obvious as to how to disable building kubectl from source, for those who wish to rely on the installed kubectl version.

@nlopezgi Mentioned there was a doc PR incoming, but figured I'd add this for tracking

**Comment by nlopezgi** [comment]
thanks for creating this, will work on this PR now before I forget.

**Comment by chrislovecnm** [comment]
Should we be building kubectl from source by default?

**Comment by nlopezgi** [comment]
I changed the default for users just adding k8s_repositories() to their WORKSPACE to get the "use the one from path" to stay with the behavior before #229. Please see the PR and let me know if anyone has thoughts about it.
