### ISSUE TITLE
Please update your protobuf dependency to version 3.6.1.2

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/rules_k8s#240]
An `--incompatible_static_name_resolution` was flipped in Bazel HEAD and will be in the next Bazel release. In order for `rules_k8s` to keep working on our CI and downstream testing please update your protobuf dependency to version 3.6.1.2. See for example https://github.com/bazelbuild/rules_closure/commit/5bcff4c4001a0c4a6a10d5683b0aab7c8590e85c

Relevant error message when building with Bazel HEAD
```
INFO: SHA256 (https://codeload.github.com/google/protobuf/zip/48cb18e5c419ddd23d9badcfe4e9df7bde1979b2) = b6b42f90c60b54732f764ae875623a9b05e6eede064173c36c6fea12dd376cdd
--
  | ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/28ac1e0193e161a13127c9ba1d2c681e/external/com_google_protobuf/BUILD:573:1: Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/28ac1e0193e161a13127c9ba1d2c681e/external/com_google_protobuf/BUILD", line 573
  | internal_gen_well_known_protos_java(srcs = WELL_KNOWN_PROTOS)
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/28ac1e0193e161a13127c9ba1d2c681e/external/com_google_protobuf/protobuf.bzl", line 269, in internal_gen_well_known_protos_java
  | Label(("%s//protobuf_java" % REPOSITOR...))
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/28ac1e0193e161a13127c9ba1d2c681e/external/com_google_protobuf/protobuf.bzl", line 269, in Label
  | REPOSITORY_NAME
  | builtin variable 'REPOSITORY_NAME' is referenced before assignment.
```

On Bazel's Buildkite CI we have disabled `rules_k8s` until this issue is resolved. Thanks!

**Comment by nlopezgi** [comment]
@buchgr @meteorcloudy 
can you please check if we can turn this on again in Bazel CI and downstream testing

**Comment by buchgr** [comment]
The error persists unfortunately :\. https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/688#a09334f3-d9af-4e93-bfe2-16986da1937a Any ideas @nlopezgi ?
