### ISSUE TITLE
bazel run //path/to:target.diff command

### ISSUE THREAD

**Issue by achew22** [bazelbuild/rules_k8s#242]
Maybe it is possible and I missed it, but is it possible to do a `.diff` like you would a `.apply`? I'm trying to onboard my free standing YAML configuration into rules_k8s and I believe it will be the same, but it would be nice to know what happens if I were to apply the change in production. Is there anything like that available?

I looked in the docs on this project and also in the docs for `kubectl` to see if I could make the apply command do a diff. It looks like you can get it to do a `--dry-run` but that is entirely local.

**Comment by chrislovecnm** [comment]
Diff is not currently supported, but it is s very interesting idea.

**Comment by mariusgrigoriu** [comment]
I'd love to see (and maybe implement) a diff. 

I have a monorepo with about 35 different k8s applications that get deployed. Would be great to see a diff of what changed across multiple targets without having script something that calls each application's diff target separately. How would you go about doing that?
