### ISSUE TITLE
Expand documentation to explain how to add custom resolvers

### ISSUE THREAD

**Issue by achew22** [bazelbuild/rules_k8s#244]
In the documentation you have the helpful line

>Sometimes, you need to replace additional runtime parameters in the YAML file. While you can use expand_template for parameters known to the build system, you'll need a custom resolver if the parameter is determined at deploy time. A common example is Google Cloud Endpoints service versions, which are determined by the server.

However, it doesn't make obvious how one would actually go about doing that. Should I be making a macro that wraps the template argument in an expand template? Should I be writing my own rule that invokes rules_k8s internal methods for accessing data? It would be really great if I could just add to the substitutions dict myself when defining `k8s_defaults`. Would you be open to that as a PR?

**Comment by chrislovecnm** [comment]
I think this is a duplicate or more well written version of https://github.com/bazelbuild/rules_k8s/issues/233

We would love a PR!!! Docs, examples and tests make me happy!!
