### ISSUE TITLE
Tests failing on CI due to `docker` not found

### ISSUE THREAD

**Issue by philwo** [bazelbuild/rules_k8s#255]
Hi,

this project is failing on our CI since we moved to Docker-based containers.
The error message is:

```
...
+ docker load -i bazel-out/k8-fastbuild/bin/images/gcloud-bazel/gcloud_installer.tar
bazel-out/k8-fastbuild/bin/images/gcloud-bazel/gcloud_install.build: line 10: docker: command not found
```
(see https://buildkite.com/bazel/rules-k8s-k8s/builds/456#d888eec2-bd7d-43d8-9939-527382f726f8)

I would like to understand how we can this working again, but don't know anything about rules_k8s. 

We could maybe install Docker inside the Docker container, so you'd get the `docker` command, but AFAIK one cannot (easily?) run the Docker daemon inside a Docker container. The usual workaround seems to be to mount the host's Docker socket into the container, but I'd like to avoid that for various reasons. WDYT?

**Comment by chrislovecnm** [comment]
I’m guessing that gcloud is calling 

gcloud auth configure-docker

That is configuring the auth it uses for the container registry, and have nothing to do with running starting a container.

I am not seeing docker in our bazel container, but I could be wrong.

What happens if you install docker?

**Comment by nlopezgi** [comment]
We have one target that builds an image using rules_docker + some rules that do require docker. Removed that target from CI in #256 , will try to add it later to an RBE build
