### ISSUE TITLE
Support stamping image tag

### ISSUE THREAD

**Issue by mariusgrigoriu** [bazelbuild/rules_k8s#266]
Some like to stamp image tags with their build numbers. It seems that`k8s_object` doesn't support stamping in the `image` argument. Would this be desirable?

**Comment by nlopezgi** [comment]
@chrislovecnm thoughts?

**Comment by chrislovecnm** [comment]
Yes it would be a great option

**Comment by lzaldivarkt** [comment]
it would be great to have this. Using a single tag for images is an antipattern. We should be able to create a new tag for every new build, for example .

**Comment by nlopezgi** [comment]
HI @lzaldivarkt, @chrislovecnm , @mariusgrigoriu ,
Thanks for the comments on this issue.
We are not currently actively investing time into building new features for rules_k8s. I'd be happy to work with anyone that wants to design and implement this feature!

**Comment by mariusgrigoriu** [comment]
Thanks for letting us know. What should we expect for rules_k8s going forward?

**Comment by nlopezgi** [comment]
We are keeping it up with Bazel releases and making sure things dont break, but don't have any plans to build new features atm.

**Comment by zoidbergwill** [comment]
Is this fixed by https://github.com/bazelbuild/rules_k8s/pull/423?

**Comment by mariusgrigoriu** [comment]
Yes, it is implemented.
