### ISSUE TITLE
Get all tests passing with --incompatible_disable_legacy_cc_provider for Bazel 0.25.0

### ISSUE THREAD

**Issue by oquenchil** [bazelbuild/rules_k8s#272]
It seems that rules_k8s will start breaking with the next Bazel release 0.25 because of an incompatible change (https://github.com/bazelbuild/bazel/issues/7036)

`ERROR: /home/bazel/.cache/bazel/_bazel_bazel/16b7e4e760c79bffb5052db686d1c0f9/external/org_golang_x_sys/unix/BUILD.bazel:3:1: in libs attribute of _cgo_collect_info rule @org_golang_x_sys//unix:go_default_library%android_arm64%cgo_info: '@org_golang_x_sys//unix:go_default_library%android_arm64%cgo_c_lib' does not have mandatory providers: 'cc'. Since this rule was created by the macro 'go_library_macro', the error might have been caused by the macro implementation in /home/bazel/.cache/bazel/_bazel_bazel/16b7e4e760c79bffb5052db686d1c0f9/external/io_bazel_rules_go/go/private/rules/cgo.bzl:695:16`

I don't see any errors for rules_go, so it could be that rules_k8s is using an old version of rules_go?

**Comment by nlopezgi** [comment]
Thanks for opening this issue. Its likely we have not updated to latest version of rules_go. Want to volunteer a PR to update? Otherwise we'll try to get to this soon.
