### ISSUE TITLE
Istio Samples

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_k8s#31]
This is basically an umbrella item to consider how these rules will interact with Istio.  Perhaps what we have is enough, and we just need samples.  Perhaps Istio is special enough that we want `rules_istio`.

**Comment by mattmoor** [comment]
It looks like Istio `RouteRule` is a CRD, so these should just work with them.  I'll leave this open to add some samples.

**Comment by pcj** [comment]
Trying to figure out how istio manual injection jibes with the rules_k8s resolver concept.  

Is there an example of using istioctl as a resolver?  

(Is this even the correct use case for a resolver?)

**Comment by mattmoor** [comment]
To preface, I wouldn't say that the story for custom resolvers is fully baked (or documented) by any means.  It was exposed as a sort of escape hatch to do other non-hermetic stuff during `bazel run` of the target.

I haven't messed that much with injection, but it feels closer to templating than resolution to me.  Is there something the manual injection would need to do that's non-hermetic?
