### ISSUE TITLE
renovatebot commit includes a bad SHA

### ISSUE THREAD

**Issue by greggdonovan** [bazelbuild/rules_k8s#322]
The recent renovatebot commit [updating `rules_go`](https://github.com/bazelbuild/rules_k8s/commit/50fb3c2f868fcd0b5c3f223ac19ba72db1f6eb7d) had an incorrect SHA256 [here](https://github.com/bazelbuild/rules_k8s/commit/50fb3c2f868fcd0b5c3f223ac19ba72db1f6eb7d#diff-34677541ac759c7a9ec13fe92161ac4bR56).

This is easily fixed, but perhaps there's a broader bug in renovatebot worth looking into? Perhaps it's re-using the SHA for the first url rather than re-calculating the 2nd one? I'm not sure where the renovate Bazel updater source is.

**Comment by nlopezgi** [comment]
Hi @greggdonovan ,
thanks for opening this issue! I have sent a PR fixing the issue in our repo (i.e., make sure that we are pulling from the same URL in both places). I'll open up an issue in the renovate bot repo soon as well.
