### ISSUE TITLE
E2E flakes

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_k8s#341]
We are getting errors like 

kubectl --namespace=build-1129779148202446848 get service hello-http-staging -o 'jsonpath={.status.loadBalancer.ingress[0].ip}'
+ [[ -z '' ]]
+ echo 'service has not yet received an IP address, sleeping for 5s...'
service has not yet received an IP address, sleeping for 5s...
+ sleep 10
{"component":"entrypoint","level":"error","msg":"Process did not exit before 15s grace period","time":"2019-05-18T18:02:15Z"}

Waiting 15 seconds probably is not enough.

**Comment by nlopezgi** [comment]
@smukherj1 fixed the issue. closing
