### ISSUE TITLE
Support stamping substitutions

### ISSUE THREAD

**Issue by christian-roggia** [bazelbuild/rules_k8s#351]
This issue is somehow related to https://github.com/bazelbuild/rules_k8s/issues/266.

It would be nice if the following example was possible:
```
k8s_object(
    ...
    substitutions = {
        "%{expand_template_variable}": "{stamp_variable}",
    },
    ...
)
```

This is especially useful if you want to embed information inside the YAML that is coming from the workspace.

**Comment by nlopezgi** [comment]
Hi, I'd be happy to review any PRs you want to send to support this.
