### ISSUE TITLE
Building newest kubectl needs io_k8s_repo_infra

### ISSUE THREAD

**Issue by codesuki** [bazelbuild/rules_k8s#358]
The workaround is adding the following to the project WORKSPACE.
```
http_archive(
    name = "io_k8s_repo_infra",
    sha256 = "4a8384320fba401cbf21fef177aa113ed8fe35952ace98e00b796cac87ae7868",
    strip_prefix = "repo-infra-df02ded38f9506e5bbcbf21702034b4fef815f2f",
    urls = mirror("https://github.com/kubernetes/repo-infra/archive/df02ded38f9506e5bbcbf21702034b4fef815f2f.tar.gz"),
)
```

Could be fixed with adding this to https://github.com/bazelbuild/rules_k8s/blob/master/toolchains/kubectl/kubectl_configure.bzl#L147-L166

**Comment by nlopezgi** [comment]
hi @codesuki,
thanks for opening this issue, i'd be happy to review  PR adding the missing dep!
Thanks again
