### ISSUE TITLE
rules_k8s requires --host_foce_python=PY2 to work with bazel 0.27.0

### ISSUE THREAD

**Issue by fejta** [bazelbuild/rules_k8s#378]
rules_k8s depends on rules_docker which depends on `--host_force_python=PY2` in order to work with bazel > 0.27.0

Can we update https://github.com/bazelbuild/rules_k8s#setup to note this requirement?

see https://github.com/bazelbuild/rules_docker/issues/842 and https://github.com/bazelbuild/bazel/issues/7899 for more info

**Comment by chrislovecnm** [comment]
@fejta should we update to support python3 rather than forcing this??

**Comment by fejta** [comment]
rules_docker requires py2, this isn't something rules_k8s can control.

**Comment by chrislovecnm** [comment]
Then we need to fix it in rules_docker....

**Comment by nlopezgi** [comment]
@chrislovecnm ,
please see the issue in rules_docker. This is not an easy issue to solve and we are working on it, but will take several more weeks - months to land. So for now we will need to have this for rules_k8s. I'll prepare a PR in a bit to update docs.
