### ISSUE TITLE
Image name used twice, replaced once

### ISSUE THREAD

**Issue by borg286** [bazelbuild/rules_k8s#395]
In the resolver you reuse the container for both marking images that have been referenced as well as a container for doing mapping between an image name and the digest
https://github.com/bazelbuild/rules_k8s/blob/master/k8s/resolver.py#L192
Instead it should preserve the map of images to their digests, then use a separate set of images that have been observed.  You can then use set substraction to find the list of images that were never used in substitution.

**Comment by nlopezgi** [comment]
Hi @borg286 ,
We're not actively planning on doing much feature development / improvements on these rules. I'd be happy to review a PR you send to implement the improvements you suggest!

**Comment by zoidbergwill** [comment]
It looks like the resolver moved from Python to Go? Is this still a bug?

**Comment by borg286** [comment]
No. Please resolve

**Comment by nlopezgi** [comment]
Thanks for creating this issue. We would welcome any PRs you want to send to fix this!
