### ISSUE TITLE
Failing go dependencies

### ISSUE THREAD

**Issue by ronaldmiranda** [bazelbuild/rules_k8s#475]
Bazel Version:  0.28.1 

```
ERROR: /root/.cache/bazel/_bazel_root/b6f7609a6ec784840d69de16ffda46a5/external/io_bazel_rules_k8s/k8s/k8s_go_deps.bzl:42:9: //external:com_github_google_go_cmp: no such attribute 'sum' in 'go_repository' rule
ERROR: /root/.cache/bazel/_bazel_root/b6f7609a6ec784840d69de16ffda46a5/external/io_bazel_rules_k8s/k8s/k8s_go_deps.bzl:42:9: //external:com_github_google_go_cmp: no such attribute 'version' in 'go_repository' rule
```

**Comment by nlopezgi** [comment]
You probably need to use a more recent Bazel version, also check if your rules_k8s setup (call to repositories.bzl) is properly done in your workspace file. If you're pulling rules_go directly in your workspace, make sure it's a recent version, or put the call to rules_k8s repo higher in your workspace file. If that all fails, post a full workspace file here and we'll help you debug.
