### ISSUE TITLE
Lots of duplication due to "cluster"

### ISSUE THREAD

**Issue by TannerYoung** [bazelbuild/rules_k8s#502]
I would love to see a best practices for how to structure code. Perhaps this is out of scope, but even a non-trivial example would be excellent to see (base kubernetes files, with overlays for dev / prod).

I find the rule duplication for prod / dev to be frustrating, considering the only difference is usually the "cluster" field. This means I have two (or three w/ staging) rules that I need to maintain each just to have a separate cluster, one for each file I have

I attempted to extend this with different bazel rules, only to realize that the object_k8s rules can't be called within rules themselves (only macros).

I would love to be able to say:

```
objects_k8s(
   name = "dev"
   templates = [
     ... base templates to include
     ... dev templates to include (local persistent volumes)
   ],
   cluster = "minikube"
),

objects_k8s(
   name = "prod"
   templates = [
     ... base templates to include
     ... prod templates to include (custom storage classes for cloud)
   ],
   cluster = "my-prod-cluster"
)
```

Thanks for any advice!

**Comment by flolu** [comment]
Any updates on this? I am facing the same issue!

**Comment by fejta** [comment]
Use a macro for this.

Create `whatever.bzl` and declare a macro (`my_k8s_object` in this example):

```python
load("@rules_k8s//k8s:object.bzl", "k8s_object")
def my_k8s_object(
  name, templates, cluster=None, **kwargs):
  if cluster:
   fail("do not set cluster")
  dev_templates = # whatever
  k8s_object(
    name = name+".dev",
    cluster = "minikube",
    templates = templates + dev_templates,
  )
  k8s_object(
    name = name+".prod",
    cluster = "my-prod-cluster",
    templates = templates + prod_templates,
  )
```

now switch your `BUILD` files from this:
```python
load("@rules_k8s//k8s:object.bzl", "k8s_object")
k8s_object(name = "foo-prod", cluster="prod", ...)
k8s_object(name = "foo-dev", cluster="minikube", ...)
```

to this:
```python
load("//path/to/whatever.bzl", "my_k8s_object")
my_k8s_object("foo", ...) # no cluster repetition
```

More info: https://docs.bazel.build/versions/master/skylark/macros.html

**Comment by fejta** [comment]
A real world example of this is here: https://github.com/kubernetes/test-infra/blob/35cfa7b7d66098fabedb8fb1c0e15be29088971e/config/prow/cluster/BUILD.bazel

Follow the definition of `release()` in `prow/def.bzl` etc.

Not solving exactly the same problem but you can write a macro that satisfies your needs.
