### ISSUE TITLE
Cloud Build Bazel Error: “kubectl toolchain was not properly configured so apply cannot be executed”

### ISSUE THREAD

**Issue by flolude** [bazelbuild/rules_k8s#512]
I am trying to deploy to my Kubernetes cluster.

Thus I have this `cloudbuild.yaml` file:

```
steps:
  - name: gcr.io/cloud-builders/bazel
    args: ['run', '//:kubernetes.apply']
```
(`//:kubernetes` is just a [`k8s_objects`][2])

---

Although the Cloud Build succeeds, I get those errors:
```
Target //:kubernetes.apply up-to-date:
  bazel-bin/kubernetes.apply
INFO: Elapsed time: 29.863s, Critical Path: 0.14s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/kubernetes.apply
INFO: Build Event Protocol files produced successfully.
INFO: Build completed successfully, 1 total action
kubectl toolchain was not properly configured so k8s_deployment.apply cannot be executed.
kubectl toolchain was not properly configured so k8s_service.apply cannot be executed.
kubectl toolchain was not properly configured so projection_database_k8s_deployment.apply cannot be executed.
kubectl toolchain was not properly configured so projection_database_k8s_service.apply cannot be executed.
kubectl toolchain was not properly configured so k8s_deployment.apply cannot be executed.
kubectl toolchain was not properly configured so k8s_service.apply cannot be executed.
kubectl toolchain was not properly configured so k8s_deployment.apply cannot be executed.
kubectl toolchain was not properly configured so k8s_service.apply cannot be executed.
kubectl toolchain was not properly configured so event_store_k8s_deployment.apply cannot be executed.
kubectl toolchain was not properly configured so event_store_k8s_service.apply cannot be executed.
kubectl toolchain was not properly configured so k8s_deployment.apply cannot be executed.
kubectl toolchain was not properly configured so k8s_service.apply cannot be executed.
kubectl toolchain was not properly configured so event_store_k8s_deployment.apply cannot be executed.
kubectl toolchain was not properly configured so event_store_k8s_service.apply cannot be executed.
kubectl toolchain was not properly configured so k8s_deployment.apply cannot be executed.
kubectl toolchain was not properly configured so k8s_service.apply cannot be executed.
kubectl toolchain was not properly configured so event_store_k8s_deployment.apply cannot be executed.
kubectl toolchain was not properly configured so event_store_k8s_service.apply cannot be executed.
```
[Here](https://00e9e64bac6fee38033ab24b94f9a27b8f2e4e466a5b2cd4ce-apidata.googleusercontent.com/download/storage/v1/b/64811142611.cloudbuild-logs.googleusercontent.com/o/log-4eb9f08f-5452-4aa8-ac79-00722b4f2fb6.txt?qk=AD5uMEs_vd1rIetasU2c4wOAwfKI4NKwdT_gUHL3CK5OuYKf920BNeUxL0GlNCo14_K5hdOoxvu8wgZpMeHkq0xI024TNCxq6AInMVBKhgKKpfn6dqPljbDtuCfnm9XU9rnAKuYRhXQG2oFSsjfpbAYtcp2B298igRbiAc3mVU2whaVT8lnuxvkeTVZfTSlXlQM51ZQiWCtvsXHQbStFQfIbUH7HK8G9WeONKaNizBiR493eF9K_3dQOeNlpR9iLt6B6Oxt2Z3ohVazg4sjc_ZW9OjwjaUKsbhd_Eo8H4UIcCLYUnqUdS8dEGgQT3b9wCSkY9DflH3ffutKWgj67eezqoEX7B2se5kCqLe6uJnMoi3v-cJIm0o1M3muOVY9tBAfDK2l3Mzdci_vAfsvIQgm2D7teAB3QYaGBLTBsXU2H5mi1Piour-ibcQL3E5LRsTVENfsWFYG716PZ3SnNL54ZGxWmLkl_qAwqreszk63e5KoV7yaFaJGe5YGQyJLZ_uNkw6G8CYhIDYGl6fpEVHQBAh6JR_brZpTGwSdZhx9EKzbIxTBmpUdDP4KyRKIxRxN_W3gi58tLTSi1vAcczWPxNSwjTqweoDOrPdHqelTCEcDrWUl4ORlpu_QxQLtuT1Ogap5V1Ebhg5d-bdvz94P8gdMFafrf65-Z0wDfij9M-fldwuBRh9FvUjcTfyzYjBVEca7XwwRAibUPFZnlX0tNYnor5m5ne0otvUbH0rXzJxuLYZo_O2nQvKWH5MTqm5XgEU4Ul3QIs_nyGc6lvsl92QsZE4ndwOxNLWrzJxsyb1OJe3pavLpKnmcfw-14CuCpLbNN9PE0w0UWLXNRj87mmechkYfEwyRyJAFi0NTu2kRkAjTNuduRBE3ZmDeHozLJ30g8-g8B) is the full log.
I also get a warning from the bazel cache:
```
DEBUG: /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/io_bazel_rules_k8s/toolchains/kubectl/kubectl_toolchain.bzl:28:9: No kubectl tool was found or built, executing run for rules_k8s targets might not work.
```

P.S.: I get the same errors when using `//:kubernetes.create`

# My setup
**Deployments**
```
load("@io_bazel_rules_k8s//k8s:object.bzl", "k8s_object")
k8s_object(
  name = "k8s_deployment",
  kind = "deployment",
  cluster = "gke_cents-ideas_europe-west3-a_cents-ideas",
  template = ":ideas.deployment.yaml",
  images = {
    "gcr.io/cents-ideas/ideas:latest": ":image"
  },
)
```
**Services**
```
k8s_object(
  name = "k8s_service",
  kind = "service",
  cluster = "gke_cents-ideas_europe-west3-a_cents-ideas",
  template = ":ideas.service.yaml",
)
```
**Aggregations**
```
load("@io_bazel_rules_k8s//k8s:objects.bzl", "k8s_objects")
k8s_objects(
    name = "k8s",
    objects = [
      ":k8s_deployment",
      ":k8s_service",
    ]
)
```
**Final composition**
```
k8s_objects(
    name = "kubernetes",
    objects = [
        "//services/ideas:k8s",
        # ...
    ]
)
```

  [1]: https://github.com/bazelbuild/rules_k8s
  [2]: https://github.com/bazelbuild/rules_k8s#multi-object-actions

**Comment by nlopezgi** [comment]
This is probably a problem with how you setup these rules in your Workspace. Please double check your setup matches the instrucionts in the readme or otherwise post here the contents of your workspace to help you better.

**Comment by flolude** [comment]
Ok, I've updated the issue with my setup and an the full log.
But what is weird is that it works fine when I run `bazel run //:kuberentes.apply` from my machine locally.

**Comment by nlopezgi** [comment]
Your machine probably has kubectl installed while the Bazel container does not. You can extend the container to install the necessary tool or you can have the rules build it from source. See here (https://github.com/bazelbuild/rules_k8s/blob/master/toolchains/kubectl/README.md) for details about how to build kubectl from source. Closing, but let me know if you run into other issues to reopen.

**Comment by flolude** [comment]
I've copied 
```
load("@io_bazel_rules_k8s//toolchains/kubectl:kubectl_configure.bzl", "kubectl_configure")

kubectl_configure(name="k8s_config", build_srcs=True)
k8s_repositories()

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")

go_rules_dependencies()
go_register_toolchains()
```

into my workspace file. Then an error told me that I have to change `@io_bazel_rules_go//go:def.bzl` to `@io_bazel_rules_go//go:deps.bzl`.

And now I get this error:
```
ERROR: /home/flolu/.cache/bazel/_bazel_flolu/2d92189468588702b7bac6d93cc5343a/external/io_kubernetes/staging/src/k8s.io/apiserver/pkg/util/flag/BUILD
:23:1: error loading package '@io_kubernetes//staging/src/k8s.io/apimachinery/pkg/util/sets': Unable to find package for @io_kubernetes_build//defs:go.bzl: The repository '@io_kubernetes_build' could not be resolved. and referenced by '@io_kubernetes//staging/src/k8s.io/apiserver/pkg/util/flag:go_default_library'
ERROR: Analysis of target '//:kubernetes.apply' failed; build aborted: error loading package '@io_kubernetes//staging/src/k8s.io/apimachinery/pkg/uti
l/sets': Unable to find package for @io_kubernetes_build//defs:go.bzl: The repository '@io_kubernetes_build' could not be resolved.
INFO: Elapsed time: 0.246s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (4 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (4 packages loaded, 0 targets configured)
```

**Comment by nlopezgi** [comment]
Thanks for noting this issue. We have some values out of date in https://github.com/bazelbuild/rules_k8s/blob/master/toolchains/kubectl/defaults.bzl and the docs are also outdated. Sending a PR to update + add tests so that we don't regress.

**Comment by flolude** [comment]
Do you think you can do it until tomorrow? Not a big deal if not :smile: Just want to know

**Comment by nlopezgi** [comment]
ugh, seems getting this working again is not trivial. From what I can gather after looking at this for about 1h, it seems we can no longer compile kubectl as an external repo.
The issue we have is the defaults we used to have that worked (https://github.com/bazelbuild/rules_k8s/blob/master/toolchains/kubectl/defaults.bzl) no longer work as a result of a combination of https://github.com/bazelbuild/rules_k8s/pull (which partially updated to support v1.14.3, but did not update defaults.bzl) + changes in bazel versions. i.e., trying to build reverting https://github.com/bazelbuild/rules_k8s/pull results in a bazel compatibility error related to  https://github.com/kubernetes/repo-infra, but updating https://github.com/kubernetes/repo-infra results in a different error: 
```
E0203 15:07:25.311001       5 main.go:52] Error: Failed making a parser: unable to add directory "k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets/types": unable to import "k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets/types": cannot find package "k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets/types" in any of:
	external/go_sdk/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets/types (from $GOROOT)
	bazel-out/k8-fastbuild/bin/external/io_kubernetes/staging/src/k8s.io/apimachinery/pkg/util/sets/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets/types (from $GOPATH)
Target @io_kubernetes//cmd/kubectl:kubectl failed to build
```
I searched for this error message and it seems this has been seen before when building kubernetes packages as an external repo: https://github.com/kubernetes/kubernetes/issues/37598

Probably the best course of action will be to start a new issue in kubernetes repo to see if they can provide support for building kubectl again as an external repo. But tbh, I do not have the cylces atm to do this task properly: not just fixing in upstream, but also figuring out a way to test this properly and to update it with new kubernetes releases. For now, your best bet will be to install kubectl in the container. Now, if you have the cycles to try to fix this, I'll be happy to work with you to make this happen.

**Comment by flolude** [comment]
Alright. I understand :smile: 

>  For now, your best bet will be to install kubectl in the container.

Could you provide a small sample on how such a `Dockerfile` would look like. Or where I can find resources about it?

**Comment by nlopezgi** [comment]
I don't have an example at hand. I would just look at the instructions to install kubectl and try to replicate that in a docker file using the Bazel container as base

**Comment by flolude** [comment]
So here is the Dockerfile I came up with:
```
FROM gcr.io/cloud-builders/bazel

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/kubectl
```

I pushed it to GCR and changed my `cloudbuild.yaml` to:
```
steps:
  - name: eu.gcr.io/cents-ideas/bazel-kubectl
    args: ["run", "//:kubernetes.apply"]
```
I firstly noticed, that the step took way longer than before. However at the end it throws an error:
```
$ /usr/local/bin/kubectl --kubeconfig= --cluster=gke_cents-ideas_europe-west3-a_cents-ideas --context= --user= apply -f -
error: cluster "gke_cents-ideas_europe-west3-a_cents-ideas" does not exist
```

[Here](https://00e9e64bac389a379917c629a22bd56b248c258ede42cf265c-apidata.googleusercontent.com/download/storage/v1/b/64811142611.cloudbuild-logs.googleusercontent.com/o/log-bb2f4b6f-84c2-4f56-af89-15a305e536e0.txt?qk=AD5uMEu_YRlHAfSU5xwyiKmKh8lsG_Gb6O2Q114junmxLrr_VyNhbo_udKtW0yniyjEeWqRQDe-o2NohuW6dXWXmXvyvInr7nimY35qmp-KsvBdWmbCPs-eAcqz6TTk65lcEz-3CwYr7LgKFx0QCOHvZQEzMC6cDquYJNOV6oTGurHmt67gsKkf5DHLiZ7cCdGPsoucsZoByVL6Bf95bfCOch0TByIeQdnkNSVJCn-uoa7JAe3n9ge0TBh01frBLXraYxW_3T9EYsAkNA5vDkdA-UIckqXy86rloR4bruDv_bBwYdqgUkkJ1sl83BDpfT5rbTim11lfeF9a1lbvNPWXB3dO7lfjiiqPIcsDaPpM4V5dRy0InSHO7AYhoJom6chfj-MXLZfcDeuUZdqW2845BGOijkFp0d5vB_YVHp47dMAxI8TYJztiY5ktgQ7n3DzG4aynzLKTXgn6BLGpZqkz70JFW0ZMTE0Gr2afsoIXN1rZeI-BkDyZqs4MXd3m6HfSnO0o9z08IlWgNwzNUf68zTO2gk2BFA1QVvbOFFdfTl9z0wDIMdBRT7vHqgTGXF1bhjK1fWhROAxsJdOQp3qrFftLPFE2POwiFXG-wAqTYULN6usLlAcPLyJcU0VzGmNaDovZdXXzYtcdSzmCgIC6fk-_cOJiq6RsicK_co3sevGqqjL3Hehba-VxyLw930GyuwtzC6zVst3p9-RbKg9xw3tzznikg8q7hIOu9leLfAG7LzmejLkB7dKSrDKUBVDLDtxNzRzK2pNU9D-ErBZcvb2o8qRNWoMrbiZaU0l3cRDRLlrRJYSFt90PbsfHBmyZXcYHSnXyg6rQB08sWq_MM0awUySouQ3IYJZQhNfXFmFUUoAFtafwRC4po1gbzxBzjhtpw6WKj) is the full log.

**Comment by flolude** [comment]
I made it work with a custom docker image with the help of [this](https://stackoverflow.com/a/60054216/8586803) answer.
But now when I first run my tests and then apply the kubernetes configurations, the build takes longer than 10 minutes and thus times out.

Do you have any suggestions on how to cut back the time? I am already using a remote cache and it's still very slow :disappointed:

**Comment by nlopezgi** [comment]
We dont really do support here for GCB, but I could provide some basic advice: Are you installing kubectl as part of the build? You could do that in a separate build and upload your image to GCR and then just run the Bazel command in a different build. You can also set the timeout for your build to be longer than 10 minutes in the cloudbuild.yaml iirc. 

Closing this as the original issue has been resolved and I have opened https://github.com/bazelbuild/rules_k8s/issues/520 to track the problem with building kubectl from source. If you have other questions about optimizing your build on GCB please ask using their support channels.

**Comment by alwaysprep** [comment]
@flolu If you do not apply it in the first step, you can redirect the stdout of bazel run command to a file. In the second step, you can use cloud-builders/kubectl to apply the output of the first step. This is going to be faster since the cloud build will not need to pull the images.


```
steps:
  - name: gcr.io/cloud-builders/bazel
    args: [
      "run", 
      "//:kubernetes", "> kubernetes.yaml"
    ]
  - name: gcr.io/cloud-builders/kubectl
    args: [
      "apply",
      "-f",
      "kubernetes.yaml"
    ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=<your_cluster_zone>"
      - "CLOUDSDK_CONTAINER_CLUSTER=<your_cluster_name>"

```

**Comment by flolu** [comment]
@alwaysprep I haven't tried it yet, but this seems like a really good idea! Thank you.
