### ISSUE TITLE
kubectl toolchain_type //visibility:public ?

### ISSUE THREAD

**Issue by kwestb** [bazelbuild/rules_k8s#530]
Would the maintainers consider making [`@io_bazel_rules_k8s//toolchains/kubectl:toolchain_type`](https://github.com/bazelbuild/rules_k8s/blob/26b1b471b4c2af39c4e2fedb2b25a3940b531a99/toolchains/kubectl/BUILD#L22)
```
visibility = ["//visibility:public"],
```

I'd like to create my `toolchain` targets in my own Bazel packages that depend on `@io_bazel_rules_k8s//toolchains/kubectl:toolchain_type`, but it isn't visible for extension.

**Comment by fejta** [comment]
Sure, send a PR?
