### ISSUE TITLE
Cluster does not exist

### ISSUE THREAD

**Issue by markabdallah** [bazelbuild/rules_k8s#555]
I currently have my BUILD file configured: 

```
k8s_object(
  name = "k8s_deployment",
  kind = "deployment",
  template = "kubernetes/dev/http_deployment-dev.yaml",
  cluster = "gke_company-microservices_us-east4-c_dev-microservices",
  images = {
    "company/product-price-microservice:$(tag)": ":price_service_image",
  },
)

k8s_object(
  name = "k8s_config",
  kind = "configmaps",
  cluster = "gke_company-microservices_us-east4-c_dev-microservices",
  template = "kubernetes/dev/http_config-dev.yaml",
)

k8s_objects(
    name = "deploy",
    objects = [
      ":k8s_config",
      ":k8s_deployment",
    ]
)
```

The problem is when I run the command: bazel run //deploy.apply. I get the error

`error: cluster "gke_company-microservices_us-east4-c_dev-microservices" does not exist`

It's running the command: `/usr/bin/kubectl --kubeconfig= --cluster=gke_company-microservices_us-east4-c_dev-microservices --context= --user= apply / -f -`

If I use kubectl --cluster="gke_company-microservices_us-east4-c_dev-microservices" apply -f . It works...

**Comment by markabdallah** [comment]
I was able to fix the problem, but now I'm faced with another issue. Like I said it's running the command `/usr/bin/kubectl --kubeconfig= --cluster=gke_company-microservices_us-east4-c_dev-microservices --context= --user= apply / -f -`

So now, I'm getting the error: `error: Unexpected args: [/]` Not sure why it is adding the `/` after `apply`

**Comment by fejta** [comment]
Do you have a repo that reproduces this issue?
