### ISSUE TITLE
The specified rules_docker version will not work with the upcoming release of Bazel

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/rules_k8s#569]
The next release of Bazel will remove @bazel_tools//third_party/py/gflags.
That forced an update of rules_docker.
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1531#94f5ac34-18d0-4eac-af7a-322acde84841

**Comment by fejta** [comment]
We auto-update to the latest rules_docker release. Please work with that repo to publish a release that includes any necessary fixes, at which point this repo will update to consume it.
