### ISSUE TITLE
Cleanup / auto-delete resources?

### ISSUE THREAD

**Issue by uhthomas** [bazelbuild/rules_k8s#609]
I'm looking at moving from using flux, to `rules_k8s`. Flux keeps the cluster exactly in-sync with the git repository, ensuring everything is up to date, and if manifests have been deleted, then the corresponding resources are also removed.

Is this possible with `rules_k8s`?

**Comment by joeljeske** [comment]
I am doing this using the —prune flag built into kubectl. I have a Kustomize rule that applies common labels to a set of manifests to ensure prune works properly.

**Comment by uhthomas** [comment]
@joeljeske That's not a bad solution. I had attempted to do this on a previous cluster but forgot to do the second part, and so `--prune` wiped out everything that wasn't in Git...

**Comment by uhthomas** [comment]
I'm going to close this, as I've implemented the `--prune` solution. It's what the [Kubernetes docs](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config) recommend for declarative management.

I'm using CUE to apply the `app.kubernetes.io/managed-by` label to all resources in the repository. This is kind of possible using a custom resolver also, but it's a little messy and there are some edge cases. For context, [I wrote one](https://github.com/uhthomas/automata/blob/4ca46a1f845355478864446d6ab2fa883bd54194/cmd/resolver/main.go) (also see the [shell script](https://github.com/uhthomas/automata/blob/4ca46a1f845355478864446d6ab2fa883bd54194/tools/resolver/resolver.sh).
https://github.com/uhthomas/automata/blob/88b112a2950c070290e2ec1f45d63a2f1f788f5d/clusters/desire/list.cue#L26

Then, I'm passing that as an explicit arg to the root `k8s_object` rule.
https://github.com/uhthomas/automata/blob/88b112a2950c070290e2ec1f45d63a2f1f788f5d/clusters/desire/BUILD.bazel#L39

Finally, I'm passing the prune flag during apply.
https://github.com/uhthomas/automata/blob/88b112a2950c070290e2ec1f45d63a2f1f788f5d/.github/workflows/apply.yaml#L18
