### ISSUE TITLE
rust_image + hellohttp example

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_k8s#62]
Maybe following [this](https://users.rust-lang.org/t/a-new-crate-simple-server-a-basic-webserver/13407)

**Comment by mattmoor** [comment]
Block on [this](https://github.com/bazelbuild/rules_rust/issues/2).

**Comment by mfarrugi** [comment]
I take it vendoring crates is too heavy for an in-repo example? 

There's also the inextensible equivalent of the other examples by doing something like [this gist](https://gist.github.com/mjohnsullivan/e5182707caf0a9dbdf2d) using std::net::TcpListener.

**Comment by mattmoor** [comment]
Yeah I don't want to vendor crates.  If they can be fetched via `http_archive` I'd be open to that.

I'm open to your example as a starting point, but would like these examples to be as close to what folks use in practice as possible (otherwise their value as a jumping-off point is limited).

@jonjohnsonjr are you interested in putting together a PR? :)

**Comment by fejta** [comment]
No thanks, the runtime internals of a docker image are irrelevant to rules_k8s. This just drags down the velocity of this repo.
