### ISSUE TITLE
Updating OWNERS file

### ISSUE THREAD

**Issue by chrislovecnm** [bazelbuild/rules_k8s#646]
Hi all!

This is a bit bold, but I care about this project.

I am noticing that this project's velocity is decreasing, and frankly, that makes me a bit sad.  Many large companies rely on these rules, and I would love to see this project maintained faster. I understand that some of the contributors and owners cannot maintain the project as actively as they would like, and I am happy to throw my hat into the ring.

If people are not comfortable adding me to the OWNERS file, I understand.  My question then is who we can add to the OWNERS file to get CI running better and more PRs reviewed.

### My Qualifications

You can see some of my issues here:
https://github.com/bazelbuild/rules_k8s/issues?q=is%3Aissue+chrislovecnm+

Also, more PR history here:
https://github.com/bazelbuild/rules_k8s/pulls?q=is%3Apr+author%3Achrislovecnm

My blog:
https://chrislovecnm.com

I am also a published manning author with a K8s book.

I will submit a PR adding myself to the owners file

**Comment by chrislovecnm** [comment]
The funny thing is that my PR is failing CI.  All I did it added myself to the OWNERS file ...

**Comment by chases2** [comment]
A big contributor to the low velocity is the broken integration tests.
https://github.com/bazelbuild/rules_k8s/issues/642
I'm certainly seeing these review requests, but nothing is merging until this gets resolved.

I would +1 your addition to the OWNER file, though. More eyes on this repository would be great.
