### ISSUE TITLE
shouldn't k8s_object.cluster fall back to k8s_defaults.cluster if not specified

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/rules_k8s#65]
https://github.com/bazelbuild/rules_k8s#k8s_object says for the `cluster` param

    If this is omitted, the create, replace, delete, describe actions will not exist.

likewise for the `namespace` param

    If this is omitted, it will default to "default".

I think these should be moved to k8s_defaults with a note in k8s_object that the defaults come from  k8s_defaults. If this is correct I can send a PR.

**Comment by mattmoor** [comment]
`k8s_defaults` simply creates an alias for `k8s_object` that passes in values for these, so I think the docs are accurate.  Maybe I'm missing an issue that pseudo-code might illuminate?

**Comment by ensonic** [comment]
It is not a big deal, but the k8s_object docs say you can't omit the cluster param, but as a matter of fact you can, if you set on in k8s_defaults().

**Comment by mattmoor** [comment]
Sure, I'm open to rewording this.  I know too much about how the sausage is made here to judge this objectively.  If you could send a PR I'd really appreciate it :)

**Comment by ensonic** [comment]
I totally missed how this works. I through of k8s_defaults as a global config.
