### ISSUE TITLE
Cutting a new release

### ISSUE THREAD

**Issue by martis42** [bazelbuild/rules_k8s#687]
Thanks to https://github.com/bazelbuild/rules_k8s/pull/675 we can now use `--incompatible_use_platforms_repo_for_constraints` together with rules_k8. That is great news as it allows a project to enforce that only the forward path regarding platforms is used.

Can you please cut a new release incorporating this change?

**Comment by BoleynSu** [comment]
Also the current latest release(0.6) prevented us from upgrading to rules_docker v.0.20.0, which is already fixed on the main branch.

**Comment by FaBrand** [comment]
Release 0.7 🎉 https://github.com/bazelbuild/rules_k8s/releases/tag/v0.7
