### ISSUE TITLE
Expand more data in the template

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/rules_k8s#70]
Since k8s_object is already running substitution to apply project settings, it would be nice if one culd substitute other variables too.

1.) One option could be to specify an extra dict of key:value pairs that it would add to the substitutions it sets up for the images:
```
k8s_object(
  name = "x-deployment",
  template = ":deployment.yaml",
  images = { ... },
  substitutions = {
    "${KEY}": "value",
  },
)

Issues:
- one might want to setup some global substitution in k8s_defaults() and add more in the aliased rule

2.) Just add ctx.vars to the list of substitutions. All keys are changed to `${key}`or something simillar.

**Comment by ensonic** [comment]
This would be useful for other projects too, see:
https://github.com/istio/istio/blob/HEAD/install/updateVersion.sh and https://github.com/istio/istio/tree/HEAD/install/kubernetes/templates

**Comment by mattmoor** [comment]
I had this in my [initial prototype](https://github.com/mattmoor/rules_k8s-OLD) and specifically avoided it because templating is a hot topic of debate in the K8s space right now.

I would much rather see this solved by templating rules that compose with (or even wrap) these rules.  `rules_jsonnet` is an option, but without [this](https://github.com/bazelbuild/rules_jsonnet/issues/29) may be of limited use.

**Comment by mattmoor** [comment]
I'm going to close this for now, but happy to continue the discussion.  If specific items fall out of further discussion, let's open more bugs.  WDYT?

**Comment by ensonic** [comment]
It is mostly a question of what the purpose of the k8s rules is. if it is to configure the k8s templates for the given build, then we should look for a templating solution as part of it. I have an idea that I will try today and keep you posted.

**Comment by mattmoor** [comment]
At this point I would say: mostly development.

I want folks to be able to build/push/deploy in a tight cycle, and for that Bazel needs to be able to model the dependencies of the K8s resources.

There is possibility for involving this in a release process to "freeze" templates via something like:
```shell
bazel run :everything > release.yaml
```
(I use that [here](https://github.com/mattmoor/warm-image#cluster-setup))


I agree that templating is often the next thing folks will want, but the DSL wars for K8s are just getting started, so my goal is for `rules_k8s` to compose with things like `rules_jsonnet` vs. embed very limited templating (as my original prototype did).

You can see some of the original discussion on this [here](https://github.com/bazelbuild/rules_docker/issues/82#issuecomment-323819655).

**Comment by mattmoor** [comment]
@ensonic ... and yes, keep me posted (but I'm OOTO starting tonight).

**Comment by ensonic** [comment]
The problem with `bazel run :everything > release.yaml` is that this assumes all those things are safe to run. We have a build with all kind of things, tools, services, .... For some targets 'run' would actually run a binary. So conceptually we want to build everything and for the k8s rules that would mean to resolve the yaml files. This still leaves the problem, that we'd need to explicitely build the k8s_objects(name="everything", ...) target to actually get the files under genfiles :/

**Comment by mattmoor** [comment]
> For some targets 'run' would actually run a binary

`bazel run` on `k8s_object[s]` just publishes the images and prints the resolved template to stdout.  It should not run any binaries.  We do this on `bazel run` because publishing is non-hermetic, and neither is accessing your credential keyring.

**Comment by skyl** [comment]
is there a way to use a list or object in the template?
