### ISSUE TITLE
k8s_defaults(image_chroot) does not support makevars

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/rules_k8s#76]
I have this in my WORKSPACE:
```
k8s_defaults(
  name = "k8s_my_object",
  cluster = "gke_$(GCP_PROJECT)_$(GCP_ZONE)_xxx",
  image_chroot = "$(GCP_REGISTRY)/$(GCP_PROJECT)/"
)
```
and in my .bazelrc:
```
build --define GCP_REGISTRY=eu.gcr.io
...
```
But those are not getting substituted. I'll probably try the workspace_status_command, but it makes things more complicated :/

**Comment by ensonic** [comment]
FYI. Since this is used in the workspace and it is a repository_rule it won't get access to ctx.vars, it only has repository_ctx:
https://github.com/bazelbuild/rules_k8s/blob/master/k8s/with-defaults.bzl

**Comment by mattmoor** [comment]
We can pass-through the string and let the underlying `k8s_object` rule resolve them.  So I'm going to close this in favor of: https://github.com/bazelbuild/rules_k8s/issues/77
