### ISSUE TITLE
k8s_object does not support makevars

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/rules_k8s#77]
`container_push()` (https://github.com/bazelbuild/rules_docker/blob/master/container/push.bzl#L62) lets you use make variables. The `registry` and `repository` parameters are straight forward to use.

When using `k8s_object()` I would need to customize `image_chroot`. This only support stamp-variables which are not documented by bazel and customizing them is not straight forward (and not documented either).

**Comment by chrislovecnm** [comment]
can we close this?
/cc @nlopezgi
