### ISSUE TITLE
Service deployment when publishing images

### ISSUE THREAD

**Issue by drigz** [bazelbuild/rules_k8s#88]
We are using Cloud Endpoints to serve an API from a Kubernetes cluster. We can't use rules_k8s to update the service as is, since we need to publish both the container image and the service definition ([see the Endpoints docs](https://cloud.google.com/endpoints/docs/openapi/deploy-redeploy-api)). The service definition is uploaded with `gcloud endpoints services deploy`, which generates a service version number that must be edited into the deployment YAML.

The best UX for deploying such a service in development would be to extend `:foo.apply` to deploy the service definition before resolving the deployment YAML. However, Bazel doesn't model dependencies of run actions on other run actions, and since service deployment is non-hermetic we can't use build-phase templating (like rules_jsonnet).

What do you think about extending rules_k8s in one of the following ways?

- to take a service definition and handle deployment for Cloud Endpoints
- to run arbitrary executables, parse key-value pairs from the output, and use this for templating

If that's out-of-scope, we'd most likely use a script that gets the YAML from rules_k8s, does further templating, and reimplements the create/apply/replace actions.

**Comment by mattmoor** [comment]
I don't have a lot of experience with Cloud Endpoints, but that seems like an annoying DevX :(

Part of me wonders if they should be hiding some of this behind a CRD that manages this stuff for you, but that doesn't solve your more immediate problem.

I think that this could probably be solved leveraging most of `k8s_object` (and making it seem like one, so you can use it in `k8s_objects`).  Today `bazel run :dev`:
1. Builds deps
1. Publishes images
1. "Resolves" the images within the template, substituting published digests.

The idea is that we could provide a `gke_service_proxy` rule (or somesuch) that in place of `images`, manages the API specification:
1. Build deps (e.g. `openapi.yaml`)
1. Publish API spec
1. Substitute the published API Spec version into the service proxy's yaml.

Again, not a lot of experience with this, but that seems like a workable idea.  WDYT?  LMK if it's unclear.

**Comment by drigz** [comment]
It took me a while, but I've got a wrapper around k8s_object that creates a script that pipes the output of k8s_object's resolver into a second resolver that handles service deployment (actually just a stub right now). Is that what you were imagining?

It looks like I'll need to duplicate a lot of the machinery for k8s actions, eg creating a new version of `create.sh.tpl` that replaces:

```
PYTHON_RUNFILES=${RUNFILES} %{resolve_script} | \
  kubectl --cluster="%{cluster}" --namespace="%{namespace}" create -f -
```

with:

```
PYTHON_RUNFILES=${RUNFILES} %{subresolve_script} | \
PYTHON_RUNFILES=${RUNFILES} %{resolve_script} | \
  kubectl --cluster="%{cluster}" --namespace="%{namespace}" create -f -
```

Could this duplication be avoided? Maybe we could change k8s_object to take an optional subresolver, which would preprocess the template YAML. Then `gke_service_proxy` only needs to provide `:name` and not `:name.create` etc. WDYT?

**Comment by drigz** [comment]
Alternatively, if the logic in `k8s_object` that creates the `name.*` rules is separated out, then `k8s_objects` (and also `k8s_endpoints_object`) could reuse it instead of creating separate scripts that call `[x + '.action' % x for x in objects]`. It might even be faster, since the resolution would be decoupled from the kubectl invocation, and you wouldn't need to parse shorthand labels.

**Comment by mattmoor** [comment]
@dgriz So my original thinking was that because a `Service` doesn't contain image references, you could simply replace `resolve_script` with your custom resolver **instead of** the standard resolver.  Does the resource coming out of your custom resolver contain image references?

I think the simplest way to test what I'm suggesting is to just change [this](https://github.com/bazelbuild/rules_k8s/blob/master/k8s/object.bzl#L176-L181) to reference your custom resolver, and see if a `k8s_object()` produces the `Service` you'd expect.

re: your second comment

What you are suggesting is that we let the `k8s_objects` rule resolve the multi-yaml document and feed that through `kubectl` directly?  I think a nuance here (that I'm not sure we should allow, since it may lead to subtle bugs) is that I could be manipulating objects across multiples namespaces or clusters (e.g. the other args aren't required to match).

I'm certainly open to refactoring here. :)

**Comment by drigz** [comment]
> Does the resource coming out of your custom resolver contain image references?

Unfortunately, yes - what I've been calling the "service version" is the version of the Cloud Endpoints service, which has to be passed on the command-line of the Extensible Service Proxy (ESP) container. As such, it has to be templated into the K8s `Deployment`, not into the K8s `Service`. "Service" is sadly overloaded here.

However, it sounds like a custom resolver can still work, if I do the following:

- k8s_object invokes custom resolver
- custom resolver is a generated shell script containing the parameters required for service definition
- custom resolver invokes the rules_k8s resolver, then does additional templating on the output

However, I'm still figuring things out here, so I'll have to try it before I'm sure it works.

> What you are suggesting is that we let the k8s_objects rule resolve the multi-yaml document and feed that through kubectl directly?

Yep, that's what I was suggesting, but you're right that it can't handle that case.

**Comment by mattmoor** [comment]
Cool, feel free to ping me if you run into trouble, it sounds like we've maybe found a good path forward.

I think making the resolver pluggable is a worthwhile refactoring, so definitely feel free to send a PR for that.  Also, if you want a home for your rule, we can probably start a `contrib/` directory on this repo, if you are interested.

**Comment by fejta** [comment]
Closing due to age
