### ISSUE TITLE
Add support for minikube

### ISSUE THREAD

**Issue by mattmoor** [bazelbuild/rules_k8s#9]
... without having to use a registry.

**Comment by mattmoor** [comment]
See [some further thoughts on this](https://github.com/bazelbuild/rules_k8s/pull/8#issuecomment-327935258) now that the `images={}` attribute is supported.

**Comment by jmhodges** [comment]
Is there a good summary of what’s blocking this? I see there’s some ideas floating around but would love to use this locally in an easy way
