### ISSUE TITLE
This repo allows merge commits

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_k8s#94]
These create a non-linear git history, so my
```
git_repository(
    name = "io_bazel_rules_k8s",
    commit = "055db1f75e00e805762798bbb14afb945955f5c1",
    remote = "https://github.com/bazelbuild/rules_k8s.git",
)
```
broke this morning now that the referenced commit isn't in the history of the master branch.

You should disable the green merge button, or whatever affordance allows merge commits.

**Comment by mattmoor** [comment]
I disabled everything but squash merges.
