### ISSUE TITLE
Command-line arguments are ignored

### ISSUE THREAD

**Issue by drigz** [bazelbuild/rules_k8s#99]
If you run:

`bazel run :k8s.create -- --save-config`

the `--save-config` is silently ignored. You won't find out until you try to `apply` a change later and it doesn't work. For this case you can just use `apply` instead of `create`, but the current behaviour masks the mistake, and passing command-line arguments through to kubectl could be useful in other cases.

I'd suggest:

- either generated scripts should print a warning/error if they get unexpected arguments,
- or they should pass them through to `kubectl`.

**Comment by mattmoor** [comment]
I like pass through.  If you are up for a PR, I'd be happy to review.

I'm not sure `--save-config` will work for the pattern that `rules_k8s` uses though because it gets the config via `STDIN`.

**Comment by ben-ng** [comment]
#132 includes a fix for passing through arguments

**Comment by chrislovecnm** [comment]
https://github.com/bazelbuild/rules_k8s/pull/224

Is in master. You can now pass in args.

Closing
